### ISSUE TITLE
timeRequired is bad written on card

### ISSUE THREAD

**Issue by fcomte** [InseeFrLab/www.sspcloud.fr#29]
with timeRequired equal to 60 i have this kind of cards

![image](https://github.com/InseeFrLab/www.sspcloud.fr/assets/48868412/b7d63059-4c3a-4fed-bf3f-c484646b5fb5)

**Comment by garronej** [comment]
Ok

**Comment by garronej** [comment]
<img width="639" alt="image" src="https://github.com/InseeFrLab/www.sspcloud.fr/assets/6702424/fc162ac7-2c0d-4343-a777-26cb8422c2d2">

<img width="1318" alt="image" src="https://github.com/InseeFrLab/www.sspcloud.fr/assets/6702424/4c4d1e5d-6007-49c7-80a9-c1c763461045">
