### ISSUE TITLE
Propositions pour les cartes de documentation sur le portail de formation

### ISSUE THREAD

**Issue by linogaliana** [InseeFrLab/www.sspcloud.fr#37]
- Dans la continuité de #36 où on a mis à jour quelques notebooks de la page de formation, j'ai deux remarques pour améliorer l'expérience utilisateur sur la page https://www.sspcloud.fr/formation

> [!NOTE]  
> Ce ne sont pas des _features_ urgentes mais ça permettrait d'avoir une page sympa à terme 😸 

## 1️⃣ Mise en forme de l'abstract

Sur le portail de formation, la mise en forme de l'abstract est foirée car `React` traite comme un _string_ et non du _markdown_ ou du _html_ le texte de l'abstract. Avoir un peu de mise en forme de l'abstract permettrait d'avoir une page plus esthétique et ainsi une meilleure expérience utilisateur.

J'ai un peu creusé, j'imagine que c'est au niveau de `DocumentationCard` dans `/src/pages/Documentation/DocumentationCard.tsx` qu'il y a moyen de modifier les choses si on désire mettre en forme le texte de l'abstract mais je suis pas assez bon en `React` pour proposer quelque chose.

## 2️⃣ Indiquer les langues disponibles pour les différents tutoriels

Une _feature_ qui pourrait être sympa: mettre les drapeaux de langue disponible pour les différentes formations en fonction des _fields_ du fichier `educationalResources`. Par exemple, si on a les clés `fr` et `en`, on aurait sur la carte:

![image](https://github.com/user-attachments/assets/d76784c1-666d-4507-824e-7efe08aea4a1)

## 3️⃣ Lancer avec VSCode / Lancer avec Jupyter

En ce qui concerne les _notebooks_, on peut les ouvrir par le biais de _Jupyter_ ou de _VSCode_. A l'heure actuelle, on n'a qu'un bouton `Lancer`. ça serait pas mal d'être plus agnostique sur l'IDE préféré des utilisateurs en proposant potentiellement un bouton "Lancer avec VSCode" et un bouton "Lancer avec Jupyter" si le concepteur de la formation a prévu ce cas là.

La carte pourrait prendre la forme suivante : 

![image](https://github.com/user-attachments/assets/25b137f1-1d23-481c-8a26-13578b91e454)

_(en un peu moins moche que ce que je viens de faire avec l'outil de développement de Firefox)_

Probablement qu'il vaut mieux que les deux boutons l'un à côté de l'autre que l'un sous l'autre. 

L'`educationalResources` _ad hoc_ pourrait prendre cette forme:

```
"deploymentUrl": {
    "fr": {
        "jupyter": "XXX",
        "vscode": "XXX"
   },
    "en": {
        "jupyter": "XXX",
        "vscode": "XXX"
   }
}
```

Qu'en pensez-vous ?

**Comment by garronej** [comment]
Salut @linogaliana!  

Merci pour l'issue!  

Je viens de push une mise a jour déjà pour que l'abstract soit formaté en Markdown.

**Comment by fcomte** [comment]
Ça peut être pas mal les p'tits drapeaux aussi

**Comment by linogaliana** [comment]
> Salut @linogaliana!
> 
> Merci pour l'issue!
> 
> Je viens de push une mise a jour déjà pour que l'abstract soit interprété comme du Markdown.

Top, je viens de voir sur https://www.sspcloud.fr/formation, merci !

**Comment by linogaliana** [comment]
Super ! J'ai mis une troisième fonctionnalité potentielle

**Comment by garronej** [comment]
Salut @linogaliana,  

J'ai implémenté les 3 features:  

<img width="1040" alt="image" src="https://github.com/user-attachments/assets/c2caf8b5-2972-462f-a497-9b34122bebe8">  

Pour faire en sorte qu'il y ai une select il suffit de renseigner un record `ideName -> LocalizedString` dans le champ `deploymentUrl`.  

Example:  

```ts
"deploymentUrl":
    "urlByIdeName": {
        "rstudio": {
            "fr": "https://datalab.sspcloud.fr/...rstudio...fr...",
            "en": "https://datalab.sspcloud.fr/...rsudio...en..."
        },
        "jupyter": "fr": "https://datalab.sspcloud.fr/...jupyter...fr..."
    }
}
```

https://github.com/InseeFrLab/www.sspcloud.fr/blob/34fa36e608ede918e8d0601d4d8bfe64f3c50fc8/src/lib/educationalResources/educationalResources.ts#L74   

Merci pour les suggestions!

**Comment by linogaliana** [comment]
C'est super comme nouvelles fonctionnalités, merci beaucoup @garronej !

**Comment by linogaliana** [comment]
@garronej je parviens bien à reproduire ton exemple de `card` avec `storybook` en local. Cependant, quand je teste l'intégration au fichier educationalResources j'ai l'erreur suivante lorsque je fais `yarn build`:

```python
$ yarn validate_educational_resources && react-scripts build && hack-gh-pages src/router.ts
$ ts-node --skip-project src/bin/validate_educational_resources.ts
/home/onyxia/work/www.sspcloud.fr/node_modules/ts-node/src/index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
src/lib/educationalResources/educationalResources_tmp.ts:576:25 - error TS2322: Type '{ rstudio: { fr: string; en: string; }; jupyter: { fr: string; en: string; }; }' is not assignable to type 'LocalizedString'.
  Object literal may only specify known properties, and '"rstudio"' does not exist in type 'Partial<Record<"en" | "fr", string>>'.

576                         "rstudio": {
                            ~~~~~~~~~~~~
577                             "fr": "https://datalab.sspcloud.fr/my-lab/catalogue/inseefrlab-helm-charts-trainings/icarius/deploiement?ide=rstudio",
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
578                             "en": "https://datalab.sspcloud.fr/my-lab/catalogue/inseefrlab-helm-charts-trainings/icarius/deploiement?ide=rstudio"
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
579                         },
    ~~~~~~~~~~~~~~~~~~~~~~~~~

    at createTSError (/home/onyxia/work/www.sspcloud.fr/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/home/onyxia/work/www.sspcloud.fr/node_modules/ts-node/src/index.ts:863:19)
    at getOutput (/home/onyxia/work/www.sspcloud.fr/node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (/home/onyxia/work/www.sspcloud.fr/node_modules/ts-node/src/index.ts:1433:41)
    at Module.m._compile (/home/onyxia/work/www.sspcloud.fr/node_modules/ts-node/src/index.ts:1617:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Object.require.extensions.<computed> [as .ts] (/home/onyxia/work/www.sspcloud.fr/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1104:12)
    at Module.require (node:internal/modules/cjs/loader:1311:19) {
  diagnosticCodes: [ 2322 ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Est-ce que j'intègre mal la clé _ad hoc_ dans le fichier educationalResources ? 

> [!NOTE] 
> _Exemple reproductible sur une branche [test-integration-educationalResources](https://github.com/InseeFrLab/www.sspcloud.fr/compare/test-integration-educationalResources) dans le commit https://github.com/InseeFrLab/www.sspcloud.fr/commit/636d010b82f7f47e4f56edd49c5fdcc5ac7d4855_

**Comment by garronej** [comment]
Hey @linogaliana, sorry I messed up the example, I edited my previous message

**Comment by linogaliana** [comment]
Thanks, worked like a charm in my local clone ! Going to update educationResources accordingly

**Comment by garronej** [comment]
Let's go! :rocket:  

Thank you for your amazing work on the educational resources!
